[package]
name = "tri-compiler"
description = "The .tri parser, template descriptors and Rust codegen for Triblenka"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
thiserror = "2.0.20"
tri-core = { version = "0.0.0", path = "../tri-core" }

[lints]
workspace = true
