[package]
name = "triblenka"
description = "An Astro-shaped web framework for Rust: server-first HTML, zero JavaScript by default"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]

[lints]
workspace = true
